# Generated by Django 5.2.7 on 2025-10-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidia_event', '0002_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
