# Generated by Django 5.2.7 on 2025-10-23 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
                ('stadion', models.CharField(max_length=100)),
                ('tahun_berdiri', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musim', models.CharField(max_length=50)),
                ('peringkat', models.PositiveIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='ibeth_clubs.club')),
            ],
        ),
    ]
