# Generated by Django 5.1 on 2025-12-16 10:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('tim_home', models.CharField(blank=True, max_length=100, null=True)),
                ('tim_away', models.CharField(blank=True, max_length=100, null=True)),
                ('skor_home', models.PositiveIntegerField(blank=True, null=True)),
                ('skor_away', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
