# Generated by Django 5.2.7 on 2025-10-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('liga', 'Liga'), ('turnamen', 'Turnamen'), ('pertandingan', 'Pertandingan')], max_length=20)),
                ('lokasi', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
            ],
        ),
    ]
