# Generated by Django 5.2.7 on 2025-10-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ibeth_clubs', '0001_initial'),
        ('rafi_player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('liga', 'Liga'), ('turnamen', 'Turnamen'), ('pertandingan', 'Pertandingan')], max_length=20)),
                ('lokasi', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peran', models.CharField(choices=[('pemain', 'Pemain'), ('kapten', 'Kapten'), ('klub', 'Klub')], max_length=20)),
                ('hasil', models.CharField(choices=[('menang', 'Menang'), ('kalah', 'Kalah'), ('juara', 'Juara')], max_length=20)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibeth_clubs.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidia_event.event')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rafi_player.player')),
            ],
        ),
    ]
