# Generated by Django 5.1 on 2025-12-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidia_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo_away',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='logo_home',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
