# Generated by Django 5.2.7 on 2025-10-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidia_event', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventParticipation',
        ),
    ]
