# Generated by Django 5.1 on 2025-12-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidia_event', '0002_event_logo_away_event_logo_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo_away',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo_home',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
