# Generated by Django 5.2.7 on 2025-10-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidia_event', '0003_alter_event_tanggal_mulai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tanggal_mulai',
            new_name='tanggal',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tanggal_selesai',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tipe',
        ),
        migrations.AddField(
            model_name='event',
            name='skor_away',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='skor_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tim_away',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tim_home',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
