# Generated by Django 5.1 on 2025-12-12 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidia_event', '0004_rename_tanggal_mulai_event_tanggal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
