# Generated by Django 6.0 on 2025-12-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nina_media_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['created_at']},
        ),
    ]
