# Generated by Django 5.2.7 on 2025-10-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nina_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilewidget',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='profilewidget',
            name='order',
        ),
        migrations.AddField(
            model_name='profilewidget',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
