# Generated by Django 5.2.7 on 2025-10-24 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata_kunci', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('pemain', 'Pemain'), ('klub', 'Klub'), ('event', 'Event')], max_length=10)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-tanggal'],
            },
        ),
    ]
