# Generated by Django 5.2.7 on 2025-10-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
                ('usia', models.PositiveIntegerField()),
                ('tinggi', models.FloatField()),
                ('berat', models.FloatField()),
                ('posisi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klub', models.CharField(max_length=100)),
                ('tahun_mulai', models.IntegerField()),
                ('tahun_selesai', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_karier', to='rafi_player.player')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=200)),
                ('tahun', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='rafi_player.player')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musim', models.CharField(max_length=20)),
                ('pertandingan', models.IntegerField()),
                ('gol', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('kartu', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistik_musim', to='rafi_player.player')),
            ],
        ),
    ]
