# Generated by Django 5.2.7 on 2025-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafi_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonstats',
            name='kartu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
