# Generated by Django 5.2.7 on 2025-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafi_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='posisi',
            field=models.CharField(choices=[('GK', 'GK (Penjaga Gawang)'), ('DF', 'DF (Bek)'), ('DFFW', 'DFFW (Bek / Penyerang)'), ('DFMF', 'DFMF (Bek / Gelandang)'), ('MF', 'MF (Gelandang)'), ('MFDF', 'MFDF (Gelandang / Bek)'), ('MFFW', 'MFFW (Gelandang / Penyerang)'), ('FW', 'FW (Penyerang)'), ('FWDF', 'FWDF (Penyerang / Bek)'), ('FWMF', 'FWMF (Penyerang / Gelandang)')], max_length=5),
        ),
    ]
