# Generated by Django 5.2.7 on 2025-10-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafi_player', '0002_player_user_alter_achievement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
