# Generated by Django 5.2.7 on 2025-10-26 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafi_player', '0003_auto_20251026_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='posisi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seasonstats',
            name='kartu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
